plugins:
  - prettier-plugin-astro
printWidth: 100
semi: false
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
overrides:
  - files:
      - '*.md'
      - '*.mdx'
    options:
      printWidth: 80
